### ISSUE TITLE
Issues reading syslog with unknown byte sequences on ruby 1.9

### ISSUE THREAD

**Issue by krorvik** [kumina/munin-puppetmaster#1]
Great little plugin - I noticed one little glitch, on ruby 1.9.3 on Ubuntu 14.04:

2014/07/05-06:45:03 [7359]  /etc/munin/plugins/puppet_totals:70:in `===': invalid byte sequence in UTF-8 (ArgumentError)

This is solved by opening the syslog in read binary mode in the plugin, like so:

```
File.open(logfile, "rb").grep(/Compiled configuration|Compiled catalog/).each do |line|
```

I have not tested this on ruby 1.8 - so be warned ;)

**Comment by Ivaylo-Korakov** [comment]
Unfortunately, this issue is really old and the project seems to be abandoned. If you are still interested in this project and if the issue persists please open a new issue and I will take a look. But for now, I am closing this issue.
